[proxy]
# Use the following line to set the private IP dynamically
# private ansible_host=$EC2_PRIVATE_IP ansible_user=ec2-user ansible_ssh_private_key_file=ssh_key_aws.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ssh_key_aws.pem -W %h:%p -q ec2-user@$BASTION_PUBLIC_IP"'

# Example of a static private IP configuration
# private ansible_host=15.161.159.67 ansible_user=ec2-user ansible_ssh_private_key_file=ssh_key_aws ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ssh_key_aws -W %h:%p -q ec2-user@$BASTION_PUBLIC_IP"'
